config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    # require title and description
     validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update create destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="nav-item active d-flex align-items-center">  
  <div class="container text-center"
  <div class="welcome">
    <% if user_signed_in? %>
      <h2> Welcome, <%=current_user.email%> </h2>
    <% else %>
      <h2> Welcome! </h2>
    <% end %>

  </div>
</div>
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CS3300</a>
   
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item active d-flex align-items-center">
          <a class="nav-link active" aria-current="page" href="#"><%= link_to "Home", root_path %>  </a>
        </li>
        <li class="nav-item active d-flex align-items-center">
          <a class="nav-link"href="#"><%= link_to "Profile", edit_user_registration_path %>  </a>
        </li>
        <li class="nav-item active d-flex align-items-center">
          <a class="nav-link" href="#"><a><% if not user_signed_in? %> <%= link_to "Login", new_user_session_path %>
          <% else %> <%= link_to "Logout", destroy_user_session_path, method: :delete %> <% end %> </a>  </a>
          
         
        
        </li>
        <li class="nav-item active d-flex align-items-center-">
        <a class="nav-link" href="#"><%= link_to "Register", new_user_registration_path %>  </a>
      </ul>
      <form class="d-flex">
       
      </form>
    </div>
  </div>
</nav>

<div class="container center"
<body>
  <%= yield %>
</body>
</div>

 
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <a style="font-family: 'Courier New', monospace;"> <%= form.label :title %> </a>
    <%= form.text_field :title, :class => 'form-control' %>
  </div>

  <div class="field">
    <a style="font-family: 'Courier New', monospace;"> <%= form.label :description %> </a>
    <%= form.text_area :description, :class => 'form-control' %>
  </div>

  <div class="container-fluid-nav text-center mt-4">
     <%= form.submit :class => 'btn btn-dark' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="col-md-4 offset-4 ">
    <div class="container-fluid-nav text-center mt-4">
        <h1 style="font-family: 'Courier New', monospace;">Editing Project</h1>
        <%= render 'form', project: @project %>
    </div>


    <div class="container-fluid-nav text-center mt-2">
         <%= link_to 'View Project', @project, :class => 'btn btn-dark' %>
        
    </div>
</div>

app/views/projects/index.html.erb
<div class="container-fluid-nav text-center">
  <p style="color: green; font-size: 30px" id="notice"><%= notice %></p>
</div>


<div class="row pt-4 pb-4">
  
<div class="card col-sm-6 ">

  </div>
</div>
  
<div class="card col-sm-6-">
  <table> 
    <tr> <h2 class="d-flex justify-content-center"> Creator: Ishmeet Singh </h2> </tr>
    <tr> <p class="text-center"> Pursuing Bachelors of Innovation in Computer Security </p> </tr>
    <tr> <p class="text-center"> ** Currently Seeking Entry Level Software Development and Computer Security positions ** </p> </tr>
  </table>


  <div class="d-flex flex-column mt-auto mb-3">
    <%= link_to "Go to my Github", "https://github.com/Ish0095", :class => 'btn btn-dark' %>
  </div>
  </div>
</div>


<div class="container mt-auto mb-auto ">
  <div class="title d-flex flex-column text-center">
    <h1 style="font-family: 'Courier New', monospace;">My Personal Projects</h1>
  </div>
  
  <table class="table">
    <thead>
        <% @projects.each do |project| %>
          <tr>
            <div class="card mt-3">
              <h5 class="card-title d-flex justify-content-center mt-3"> <%= project.title %> </h5>
              <p class="card-text d-flex text-center ml-3 mr-3"> <%= project.description %> </p>
              <div class="d-flex justify-content-center mb-2" >
                <%= link_to 'Show', project , :class => 'btn btn-outline-dark'%>
                  <div class="ml-3 mr-3"><%= link_to 'Edit', edit_project_path(project), :class => 'btn btn-outline-dark' %>
                  </div>
                <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-outline-dark' %>
              </div>
            </div>
          </tr>
        <% end %>
    </thead>
  </table>
    <div class="container-fluid-nav text-center">
      <button type="button" class="btn btn-outline-dark btn-lg" > <%= link_to 'New Project', new_project_path %> </button>
    </div>  
</div>
<br>

app/views/projects/new.html.erb
<div class="container">
    <center><h1 style="font-family: 'Times New Roman', monospace;">New Project</h1></center>
    
    <div class="col-md-4 offset-4 ">
        <%= render 'form', project: @project %>
    </div>
    
    
   
</div>

app/views/projects/show.html.erb
<title> <%= @project.title%> </title>
<p id="notice"><%= notice %></p>

<div class="container text-center">
  <p>
    <strong>Title:</strong>
    <%= @project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @project.description %>
  </p>


  <div class="container-fluid-nav text-center">
   
    <a> <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-dark' %> </a> 
  </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>